In [23]:
# Import dependencies
import requests
import json
from config import api_key, email
from pprint import pprint
import time
import os
import pandas as pd
import statistics as st

In [3]:
# Set variables to use with the URL
url_base = "https://aqs.epa.gov/data/api/annualData/byState"
param = "&param=42101,42401,42602,44201,88101"
api_key_value = "&key=" + api_key
dates = "&bdate=20200101&edate=20201231&"
state = "state="
email_address = "?email=" + email
query_url = url_base + email_address + api_key_value + param + dates + state

In [40]:
final_dict = {'State': [], 'Ozone': [], 'NO2': [], 'SO2': [], 'CO': [], 'PM 2.5': []}

# For loop to loop through the data by state code
for i in range(1,9):
    if i in [2, 3, 7]:
        continue
     
    aqi_response = requests.get(f"{query_url}0{i}")
    aqi_json = aqi_response.json()
    data = aqi_json['Data']
    print(i)
    ozone = []
    no2 = []
    so2 = []
    co = []
    pm_2_5 = []
    for element in data:
        if element['parameter_code'] == '44201':
            ozone.append(element['arithmetic_mean'])
        elif element['parameter_code'] == '42602':
            no2.append(element['arithmetic_mean'])
        elif element['parameter_code'] == '42401':
            so2.append(element['arithmetic_mean'])
        elif element['parameter_code'] == '42101':
            co.append(element['arithmetic_mean'])
        elif element['parameter_code'] == '88101':
            pm_2_5.append(element['arithmetic_mean'])
    ozone_avg = st.mean(ozone)
    no2_avg = st.mean(no2)
    so2_avg = st.mean(so2)
    co_avg = st.mean(co)
    pm_2_5_avg = st.mean(pm_2_5)
    final_dict['State'].append(i)
    final_dict['Ozone'].append(ozone_avg)
    final_dict['NO2'].append(no2_avg)
    final_dict['SO2'].append(so2_avg)
    final_dict['CO'].append(co_avg)
    final_dict['PM 2.5'].append(pm_2_5_avg)

    time.sleep(10)

1
4
5
6
8

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [41]:
test_df = pd.DataFrame(final_dict)
test_df.head()

   State     Ozone        NO2       SO2        CO     PM 2.5
0      1  0.037770  15.342895  1.093742  0.258789   8.052705
1      4  0.048894  19.499760  1.637301  0.352748   9.111642
2      5  0.037988  12.018359  0.699240  0.286940   7.983347
3      6  0.045062  14.413923  0.598520  0.345560  13.600519
4      8  0.048510  12.406450  0.882243  0.287936   7.747488

In [45]:
# For loop to loop through the data by state code
for i in range(10,57):
    if i in [14, 31, 43, 52, 54]:
        continue
     
    aqi_response = requests.get(f"{query_url}{i}")
    aqi_json = aqi_response.json()
    data = aqi_json['Data']
    print(i)
    ozone = []
    no2 = []
    so2 = []
    co = []
    pm_2_5 = []
    for element in data:
        if element['parameter_code'] == '44201':
            ozone.append(element['arithmetic_mean'])
        elif element['parameter_code'] == '42602':
            no2.append(element['arithmetic_mean'])
        elif element['parameter_code'] == '42401':
            so2.append(element['arithmetic_mean'])
        elif element['parameter_code'] == '42101':
            co.append(element['arithmetic_mean'])
        elif element['parameter_code'] == '88101':
            pm_2_5.append(element['arithmetic_mean'])
    ozone_avg = st.mean(ozone)
    no2_avg = st.mean(no2)
    so2_avg = st.mean(so2)
    co_avg = st.mean(co)
    pm_2_5_avg = st.mean(pm_2_5)
    final_dict['State'].append(i)
    final_dict['Ozone'].append(ozone_avg)
    final_dict['NO2'].append(no2_avg)
    final_dict['SO2'].append(so2_avg)
    final_dict['CO'].append(co_avg)
    final_dict['PM 2.5'].append(pm_2_5_avg)

    time.sleep(10)
final_df = pd.DataFrame(final_dict)

10
11
12
13
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
32
33
34
35
36
37
38
39
40
41
42
44
45
46
47
48
49
50
51
53
55
56

In [34]:
aqi_response1 = requests.get(f"{query_url}0{2}")
aqi_json1 = aqi_response.json()
#pprint(aqi_json)
pprint(aqi_json1["Data"][['parameter_code'] == '42602'])

{'arithmetic_mean': 4.673446,
 'cbsa': 'Birmingham-Hoover, AL',
 'cbsa_code': '13820',
 'certification_indicator': 'Certified',
 'city': 'Calera',
 'county': 'Shelby',
 'county_code': '117',
 'date_of_last_change': '2022-11-30',
 'datum': 'NAD83',
 'event_type': 'No Events',
 'exceptional_data_count': 0,
 'fiftieth_percentile': 1.3,
 'first_max_datetime': '2020-06-07 13:00',
 'first_max_n_o_datetime': None,
 'first_max_nonoverlap_value': None,
 'first_max_value': 52.1,
 'fourth_max_datetime': '2020-01-17 18:00',
 'fourth_max_value': 36.6,
 'latitude': 33.0928,
 'local_site_name': 'Lhoist, Montevallo Plant',
 'longitude': -86.8072,
 'method': 'INSTRUMENTAL - ULTRAVIOLET FLUORESCENCE',
 'metric_used': 'Daily maximum 1-hour average',
 'ninetieth_percentile': 12.8,
 'ninety_eighth_percentile': 35.4,
 'ninety_fifth_percentile': 25.2,
 'ninety_ninth_percentile': 36.6,
 'null_observation_count': 889,
 'observation_count': 7895,
 'observation_percent': 90.0,
 'parameter': 'Sulfur dioxide',
 'parameter_code': '42401',
 'poc': 1,
 'pollutant_standard': 'SO2 1-hour 2010',
 'primary_exceedance_count': 0,
 'required_day_count': 366,
 'sample_duration': '1 HOUR',
 'sample_duration_code': '1',
 'second_max_datetime': '2020-04-22 13:00',
 'second_max_n_o_datetime': None,
 'second_max_nonoverlap_value': None,
 'second_max_value': 50.3,
 'secondary_exceedance_count': None,
 'seventy_fifth_percentile': 4.3,
 'site_address': '7444 State Hwy 25',
 'site_number': '9001',
 'standard_deviation': 8.155085,
 'state': 'Alabama',
 'state_code': '01',
 'tenth_percentile': 0.3,
 'third_max_datetime': '2020-11-04 13:00',
 'third_max_value': 41.3,
 'units_of_measure': 'Parts per billion',
 'valid_day_count': 354,
 'validity_indicator': 'Y',
 'year': 2020}